version: "3"
services:
  api-docker :
    image: api-docker
    build: EasyDockerREST/
    ports:
      - "5001:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - easy-docker-net
  mysql-database:
    container_name: easy-docker-mysql
    image: mysql:8.0.19
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: always
    ports:
      - "3308:3306"
    networks:
      - easy-docker-net
    volumes:
      - ./data:/var/lib/mysql
  registry:
    container_name: registry
    image: registry
    ports:
      - "5000:5000"
    networks:
      - easy-docker-net
    volumes:
      - ./tmp-registry:/var/lib/registry

networks:
  easy-docker-net:
    